version: '3.8'

services:
  
  frontend:
    build: ./example-frontend
#    ports: 
#      - 5000:5000
    depends_on:
      - redis
  
  backend:
    build: ./example-backend
#    ports:
#      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=db
      - POSTGRES_DATABASE=postgres
    depends_on:
      - db
  
  redis:
    image: redis
    command: redis-server
    restart: unless-stopped

  web:
    image: nginx
    volumes:
    - ./templates/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
    environment:
      - NGINX_HOST=http://localhost
      - NGINX_PORT=80
    depends_on:
      - frontend
      - backend

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_HOST: db
      POSTGRES_DATABASE: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  database:
  files:
